FROM jupyterhub/jupyterhub:latest

RUN pip install --no-cache-dir \
    dockerspawner \
    jupyterhub-nativeauthenticator \
    docker \
    jupyterhub-idle-culler \
    marimo \
    marimo-jupyter-extension
