# minimal-notebook is very lightweight compared to the others
ARG BASE_IMAGE=quay.io/jupyter/minimal-notebook:latest
FROM ${BASE_IMAGE}

USER root

# 1. Copy uv binaries
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

# 2. Install ONLY the core Jupyter extensions globally
RUN uv pip install --no-cache --system \
    jupyter-scheduler \
    jupyter-resource-usage \
    jupyterlab-nvdashboard \
    ipykernel

USER ${NB_UID}